name: ncovidtracker
description: nCovid19 Tracker built using Flutter & Coronavirus Tracker API.
version: 1.0.0+1

authors:
  - Tirth Patel
repository: https://github.com/piedcipher/nCovid19-tracker
homepage: https://github.com/piedcipher/nCovid19-tracker
issue_tracker: https://github.com/piedcipher/nCovid19-tracker/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  http:
  built_value:
  built_collection:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true