name: ncovidtracker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  http:
  built_value:
  built_collection:
  url_launcher:
  shared_preferences:
  demoji:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true